name = "BackpackOnChestRedux"
prefix = "bocr"
mainprefix = "x"
author = "DerZade, mjc4wilton"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_bocr_ca.paa",
    "meta.cpp"
]

include = [
    "./include"
]

exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
sig_version = 3

# ArmaScriptCompiler steps (Disabled until HEMTT supports signing PBOs with *.sfqc files)
#prebuild = ["!compile_scripts"]
#postbuild = ["!remove_compiled_scripts"]

releasebuild = [
    "@zip bocr_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"

[scripts.compile_scripts]
steps_windows = [
    "echo STEP: Compile Arma Scripts",
    "ArmaScriptCompiler"
]
only_release = false
show_output = true

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo STEP: Remove Compiled Scripts (*.sqfc)",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
only_release = false
show_output = true
